/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F030R8T6.h"
#include "stm32f030r8t6_gpio_driver.h"
#include <stdint.h>

// ISR for EXTI Line 0 and 1 (Must be outside of main!)
void EXTI0_1_IRQHandler(void)
{
    // Clear the pending bit for the pin (e.g., Pin 0)
    GPIO_IRQHandling(GPIO_PIN_NO_0);

    // Your User Application Code Here
    // e.g., Toggle LED, set a status flag, etc.
}

int main(void)
{
    /* Loop forever */
	for(;;);
}
